# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Branch_1-Weekly Team Sync
on:
  workflow_dispatch:
#   schedule:
#     - cron: 20 07 * * 1

jobs:
  create_issue:
    name: Create team sync issue
    runs-on: ubuntu-latest
    steps:
      - name: Create team sync issue
        uses: imjohnbo/issue-bot@v3.4.4
        #@3daae12aa54d38685d7ff8459fc8a2aee8cea98b
        with:
          assignees: "alaaalsaban"
          labels: "bug"
          title: "Alaa Weekly Team Sync"
          body: |
            ### Agenda

            - [ ] Start the recording
            - [ ] Check-ins

                    
            ### Discussion Points
            Add things to discuss below

          pinned: false
          close-previous: True
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
